server:
  port: 8080

spring:
  application:
    name: mill-api
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      pool-name: Hikari
    username: mill_admin
    url: jdbc:postgresql://localhost:5432/mill_db?currentSchema=inventory
    password: password
    type: com.zaxxer.hikari.HikariDataSource
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    encoding: UTF-8
springdoc:
  swagger-ui:
    path: /swagger-ui.html